spring:
  application:
    name: store
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=store
    username: postgres
    password: HelpDesk21!
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
stripe:
 apiUrl: https://api.stripe.com
 timeout: 1000
 enabled: true
 supported-currencies: USD, EUR, GBP
payment-gateway: stripe
mail:
  host: https://smtp.gmail.com
  port: 5761