ALTER TABLE users ALTER COLUMN email TYPE VARCHAR(30);
ALTER TABLE users ALTER COLUMN email DROP NOT NULL;

ALTER TABLE users ALTER COLUMN name TYPE VARCHAR(75);
ALTER TABLE users ALTER COLUMN name DROP NOT NULL;

ALTER TABLE users ALTER COLUMN password TYPE VARCHAR(25);
ALTER TABLE users ALTER COLUMN password DROP NOT NULL;